<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <FrameworkCompatibleVersion>HighestTestedAgainst</FrameworkCompatibleVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="AsyncKeyedLock" Version="8.1.2" />
        <PackageVersion Include="DotNet.ReproducibleBuilds" Version="2.0.5" />
        <PackageVersion Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
        <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
        <PackageVersion Include="System.Net.Http" Version="4.3.4" />
        <PackageVersion Include="System.Text.RegularExpressions" Version="4.3.1" />
        <PackageVersion Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
        <PackageVersion Include="UnitsNet" Version="5.75.1" />
        <PackageVersion Include="xunit.v3.mtp-v2" Version="4.0.1" />
        <PackageVersion Include="xunit.v3" Version="4.0.1" />
        <PackageVersion Include="Microsoft.Extensions.Caching.Memory" FrameworkCompatibleVersion="$(FrameworkCompatibleVersion)" />
        <PackageVersion Include="Microsoft.Extensions.Configuration" FrameworkCompatibleVersion="$(FrameworkCompatibleVersion)" />
        <PackageVersion Include="Microsoft.Extensions.Configuration.Json" FrameworkCompatibleVersion="$(FrameworkCompatibleVersion)" />
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" FrameworkCompatibleVersion="$(FrameworkCompatibleVersion)" />
        <PackageVersion Include="Microsoft.Extensions.Http" FrameworkCompatibleVersion="$(FrameworkCompatibleVersion)" />
        <PackageVersion Include="System.Text.Json" FrameworkCompatibleVersion="$(FrameworkCompatibleVersion)" />
    </ItemGroup>
</Project>
